### ISSUE TITLE
Sidekiq Generator - NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by Richar-p** [moduloTech/modulorails#26]
Error after using sidekiq generator and trying to deploy.

```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/app/config/initializers/sidekiq.rb:1:in `<main>'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `load'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `block in load_config_initializer'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:208:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:666:in `load_config_initializer'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:619:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/engine.rb:619:in `block in <class:Engine>'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
/app/config/environment.rb:5:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/app/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:511:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
./bin/bundle:108:in `load'
./bin/bundle:108:in `<main>'
```

**Comment by winnieoursbrun** [comment]
@Richar-p  Can you share your `/app/config/initializers/sidekiq.rb` and relative file with it ?

**Comment by Ezveus** [comment]
Can't repro. Stale.
