### ISSUE TITLE
Rubocop error since Modulorails 1.4.0

### ISSUE THREAD

**Issue by chevre-a-mt** [moduloTech/modulorails#33]
Since I updated (and docker build) to modulorails 1.4.0 I have this error

```
/app # rubocop
uninitialized constant RuboCop::Lockfile::Bundler
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:66:in `rescue in parser'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:60:in `parser'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/lockfile.rb:38:in `gem_versions'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/config.rb:332:in `read_gem_versions_from_target_lockfile'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/config.rb:293:in `gem_versions_in_target'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/config.rb:309:in `read_rails_version_from_bundler_lock_file'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/config.rb:304:in `target_rails_version_from_bundler_lock_file'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/config.rb:255:in `target_rails_version'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/base.rb:264:in `target_rails_version'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:182:in `support_target_rails_version?'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:166:in `block in roundup_relevant_cops'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:161:in `select'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:161:in `roundup_relevant_cops'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cop/team.rb:88:in `investigate'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:348:in `block in inspect_file'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `each'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `flat_map'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:347:in `inspect_file'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:290:in `block in do_inspection_loop'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:324:in `block in iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:317:in `loop'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:317:in `iterate_until_no_changes'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:286:in `do_inspection_loop'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:167:in `block in file_offenses'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:192:in `file_offense_cache'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:166:in `file_offenses'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:102:in `block in warm_cache'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:627:in `call_with_index'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:597:in `process_incoming_jobs'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:577:in `block in worker'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:568:in `fork'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:568:in `worker'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:559:in `block in create_workers'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:558:in `each'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:558:in `each_with_index'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:558:in `create_workers'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:497:in `work_in_processes'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:291:in `map'
/usr/local/bundle/gems/parallel-1.24.0/lib/parallel.rb:235:in `each'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:102:in `warm_cache'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/runner.rb:75:in `run'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/command.rb:11:in `run'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli/environment.rb:18:in `run'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli.rb:118:in `run_command'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli.rb:125:in `execute_runners'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli.rb:51:in `block in run'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli.rb:77:in `profile_if_needed'
/usr/local/bundle/gems/rubocop-1.63.0/lib/rubocop/cli.rb:43:in `run'
/usr/local/bundle/gems/rubocop-1.63.0/exe/rubocop:19:in `block in <top (required)>'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/usr/local/bundle/gems/rubocop-1.63.0/exe/rubocop:19:in `<top (required)>'
/usr/local/bundle/bin/rubocop:25:in `load'
/usr/local/bundle/bin/rubocop:25:in `<main>'
```

**Comment by Ezveus** [comment]
There is no problem with Modulorails. The problem is an incompatibility between **Rubocop 1.63.0** and **Bundler 2.5**.
 
**Solution : downgrade Rubocop to 1.62.0 in your Gemfile if you're using Bundler 2.5. There is no problem with Bundler 2.4.**
